### ISSUE TITLE
Curiosity kills the cat

### ISSUE THREAD

**Issue by IkehAkinyemi** [PacktPublishing/Microservices-with-Go#1]
I have been searching for a practical Golang book on microservices, and I think this may be it. Please, when is the release date for the book?

Is there an early-access audience(readers)? I want in.

**Comment by SweetyPagaria** [comment]
Hi, Glad to know your curiosity. You can get the book at https://www.packtpub.com/product/microservices-with-go/9781804617007 or https://www.amazon.com/dp/1804617008

**Comment by IkehAkinyemi** [comment]
Thank you @SweetyPagaria
