### ISSUE TITLE
Chapter07: quick fixes for MySQL, grpcurl 

### ISSUE THREAD

**Issue by jasonsalas** [PacktPublishing/Microservices-with-Go#9]
I'm really enjoying working through the code in this book. Great job! I've noticed a couple of steps left out for Chapter 7's examples to run, so you'll need to:

- run *CREATE DATABASE movieexample* (you probably want to access the container instance to execute this command by using _mysql -uroot -ppassword_ in Docker first)
- run _go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest_ to get grpcurl on your machine

Thanks again!

**Comment by rajat-packt** [comment]
Thanks for the suggestions @jasonsalas, we have included these in the README.
Closing this issue now.

**Comment by jasonsalas** [comment]
> Thanks for the suggestions @jasonsalas, we have included these in the README.
> 
> Closing this issue now.

Awesome! Thanks much. 😎
